#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# scripts/check-sdk-drift.sh
#
# Regenerates the OpenAPI-derived TypeScript types from the current spec and
# fails with a clear message if they differ from what is committed under
# sdk/typescript/src/types/index.ts.
#
# Usage (local):
#   ./scripts/check-sdk-drift.sh
#
# Usage (CI):
#   ./scripts/check-sdk-drift.sh --ci
#
# Requirements:
#   - Node.js ≥18 with `npx` available
#   - docs/generated/openapi.json must exist (generated by the build/export step)
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPENAPI_SPEC="${REPO_ROOT}/docs/generated/openapi.json"
COMMITTED_TYPES="${REPO_ROOT}/sdk/typescript/src/types/index.ts"
TEMP_DIR="${REPO_ROOT}/.sdk-drift-check"
GENERATED_TYPES="${TEMP_DIR}/types.ts"

CI_MODE=false
[[ "${1:-}" == "--ci" ]] && CI_MODE=true

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[sdk-drift]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[sdk-drift]${NC} $*"; }
log_error() { echo -e "${RED}[sdk-drift]${NC} $*" >&2; }

# ── Pre-flight checks ──────────────────────────────────────────────────────────
if [[ ! -f "${OPENAPI_SPEC}" ]]; then
  log_error "OpenAPI spec not found at ${OPENAPI_SPEC}"
  log_error "Run 'npm run export:openapi' (or the CI generate-spec step) first."
  exit 1
fi

if [[ ! -f "${COMMITTED_TYPES}" ]]; then
  log_error "Committed SDK types not found at ${COMMITTED_TYPES}"
  exit 1
fi

# ── Prepare temp directory ─────────────────────────────────────────────────────
rm -rf "${TEMP_DIR}"
mkdir -p "${TEMP_DIR}"

log_info "Generating TypeScript types from ${OPENAPI_SPEC} …"

# ── Generate types from the OpenAPI spec ──────────────────────────────────────
# Uses openapi-typescript (no install needed — npx pulls it on demand in CI,
# and it is a devDependency in the SDK package locally).
npx --yes openapi-typescript@6 \
  "${OPENAPI_SPEC}" \
  --output "${GENERATED_TYPES}" \
  2>/dev/null

if [[ ! -f "${GENERATED_TYPES}" ]]; then
  log_error "openapi-typescript did not produce output at ${GENERATED_TYPES}"
  exit 1
fi

log_info "Comparing generated types against committed types …"

# ── Diff ───────────────────────────────────────────────────────────────────────
# Strip leading comments (timestamps etc.) before diffing so cosmetic header
# changes don't trigger a false positive.
strip_header() {
  grep -v '^\s*/\*' "$1" | grep -v '^\s*\*' | grep -v '^\s*//'
}

COMMITTED_STRIPPED="${TEMP_DIR}/committed_stripped.ts"
GENERATED_STRIPPED="${TEMP_DIR}/generated_stripped.ts"
strip_header "${COMMITTED_TYPES}"  > "${COMMITTED_STRIPPED}"
strip_header "${GENERATED_TYPES}"  > "${GENERATED_STRIPPED}"

if diff -u "${COMMITTED_STRIPPED}" "${GENERATED_STRIPPED}" > "${TEMP_DIR}/diff.patch"; then
  log_info "✅  SDK types are in sync with the OpenAPI spec."
  rm -rf "${TEMP_DIR}"
  exit 0
fi

# ── Drift detected ─────────────────────────────────────────────────────────────
log_error "❌  SDK types have drifted from the OpenAPI spec."
echo ""
echo "──── Diff (committed → generated) ────────────────────────────────────────"
cat "${TEMP_DIR}/diff.patch"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
log_warn "To fix, regenerate and commit the updated types:"
echo ""
echo "    # 1. (Re-)export the OpenAPI spec from the running app:"
echo "    npm run export:openapi"
echo ""
echo "    # 2. Regenerate the SDK types:"
echo "    npm run sdk:generate-types"
echo ""
echo "    # 3. Review the diff, then commit:"
echo "    git add sdk/typescript/src/types/index.ts"
echo "    git commit -m 'chore(sdk): regenerate types from updated OpenAPI spec'"
echo ""

if $CI_MODE; then
  log_error "CI build failed due to SDK type drift. See diff above."
fi

rm -rf "${TEMP_DIR}"
exit 1
