/**
 * Provider contract verification.
 *
 * Starts the NestJS app on an ephemeral port, then runs Pact's Verifier
 * against every pact file generated by the consumer suite.  A breaking
 * change to a covered endpoint's response shape will fail this test.
 *
 * Run: jest --testPathPattern=contracts/provider
 *
 * To add a new contract:
 *  1. Write a consumer interaction in test/contracts/consumer/
 *  2. Run the consumer suite to regenerate the pact JSON in test/contracts/pacts/
 *  3. Re-run this suite — the new interaction is verified automatically.
 */
import * as path from 'path';
import { Verifier, VerifierOptions } from '@pact-foundation/pact';
import { Test } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import * as net from 'net';
import { AppModule } from '../../../src/app.module';

async function getFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.listen(0, () => {
      const { port } = srv.address() as net.AddressInfo;
      srv.close(() => resolve(port));
    });
    srv.on('error', reject);
  });
}

describe('StellarSwipeBackend – provider contract verification', () => {
  let app: INestApplication;
  let port: number;

  beforeAll(async () => {
    port = await getFreePort();

    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleRef.createNestApplication();
    app.setGlobalPrefix('api/v1');
    await app.init();
    await app.listen(port);
  }, 60_000);

  afterAll(async () => {
    await app?.close();
  });

  it('verifies all consumer contracts', async () => {
    const pactDir = path.resolve(process.cwd(), 'test/contracts/pacts');

    const opts: VerifierOptions = {
      provider: 'StellarSwipeBackend',
      providerBaseUrl: `http://127.0.0.1:${port}`,
      pactUrls: [
        path.join(pactDir, 'mobileclient-stellarswipebackend.json'),
      ],
      logLevel: 'warn',
      stateHandlers: {
        'at least one active signal exists': async () => { /* seed handled by test DB */ },
        'signal feed content has not changed since last request': async () => {},
        'user has sufficient balance and signal is active': async () => {},
        'portfolio exists for the given wallet address': async () => {},
        'no account exists for the given wallet address': async () => {},
      },
    };

    const output = await new Verifier(opts).verifyProvider();
    expect(output).toBeDefined();
  }, 120_000);
});
