import {
  Controller,
  Get,
  Query,
  Res,
  BadRequestException,
  ForbiddenException,
  NotFoundException,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiQuery } from '@nestjs/swagger';
import { Response } from 'express';
import { readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { SignedUrlGeneratorService } from './signed-url-generator.service';

/**
 * Controller for downloading export files using signed URLs.
 * Validates the signed URL before allowing access to the file.
 */
@ApiTags('compliance/exports')
@Controller('compliance/download')
export class SignedUrlDownloadController {
  constructor(private readonly signedUrlGenerator: SignedUrlGeneratorService) {}

  /**
   * Download an export file using a signed URL.
   *
   * The signed URL must be valid and not expired. Each URL is tied to a specific export
   * and cannot be reused for other exports.
   *
   * @param token The signed URL token (generated by export endpoints)
   * @param res Express response object for file streaming
   */
  @Get()
  @ApiOperation({
    summary: 'Download export file using signed URL',
    description:
      'Downloads an export file if the provided signed URL is valid, not expired, and has not been tampered with.',
  })
  @ApiQuery({
    name: 'token',
    description: 'Signed URL token generated by export endpoints',
    required: true,
  })
  @ApiResponse({
    status: 200,
    description: 'File download initiated',
    schema: { type: 'string', format: 'binary' },
  })
  @ApiResponse({ status: 400, description: 'Invalid or malformed signed URL' })
  @ApiResponse({ status: 401, description: 'Signed URL has expired' })
  @ApiResponse({ status: 403, description: 'Signature verification failed' })
  @ApiResponse({ status: 404, description: 'Export file not found' })
  async downloadExportFile(
    @Query('token') token: string,
    @Res() res: Response,
  ): Promise<void> {
    if (!token) {
      throw new BadRequestException('Signed URL token is required');
    }

    // Validate and decode the signed URL
    let payload;
    try {
      payload = this.signedUrlGenerator.validateAndDecodeSignedUrl(token);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes('expired')) {
        throw new ForbiddenException(`Download link has expired: ${message}`);
      } else if (message.includes('signature')) {
        throw new ForbiddenException(`Signature verification failed: ${message}`);
      } else {
        throw new BadRequestException(`Invalid signed URL: ${message}`);
      }
    }

    // Verify file exists
    if (!existsSync(payload.filePath)) {
      throw new NotFoundException('Export file not found or has been deleted');
    }

    try {
      // Read file from disk
      const fileContent = await readFile(payload.filePath);

      // Determine MIME type based on format
      const mimeType = this.getMimeType(payload.format);
      const filename = this.getFilename(payload.exportType, payload.format);

      // Set response headers for file download
      res.setHeader('Content-Type', mimeType);
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
      res.setHeader('Pragma', 'no-cache');
      res.setHeader('Expires', '0');

      // Send file content
      res.send(fileContent);
    } catch (error) {
      throw new BadRequestException(`Failed to read export file: ${error}`);
    }
  }

  /**
   * Returns the MIME type for a given file format.
   *
   * @param format The file format (e.g., 'pdf', 'csv', 'json')
   * @returns The MIME type string
   */
  private getMimeType(format: string): string {
    const mimeTypes: Record<string, string> = {
      pdf: 'application/pdf',
      csv: 'text/csv',
      json: 'application/json',
      xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      xml: 'application/xml',
      txt: 'text/plain',
    };

    return mimeTypes[format.toLowerCase()] || 'application/octet-stream';
  }

  /**
   * Generates an appropriate filename for the download.
   *
   * @param exportType Type of export
   * @param format File format
   * @returns A descriptive filename
   */
  private getFilename(exportType: string, format: string): string {
    const timestamp = new Date().toISOString().split('T')[0];
    return `${exportType}-${timestamp}.${format.toLowerCase()}`;
  }
}
